[zh-tw]
  languageCode = 'zh-TW'
  languageName = '中文繁體'
  title = 'Wayne 的部落格'
  weight = 1
  [zh-tw.params]
    [zh-tw.params.sidebar]
      subtitle = '記錄並分享日常'
  [[zh-tw.menu.main]]
    identifier = 'home'
    name = '主頁'
    url = '/'
    weight = 1
    [zh-tw.menu.main.params]
      icon = 'home'
  [[zh-tw.menu.main]]
    identifier = 'archives'
    name = '歸檔'
    url = '/page/archives/'
    weight = 2
    [zh-tw.menu.main.params]
      icon = 'archives'
  [[zh-tw.menu.main]]
    identifier = 'search'
    name = '搜索'
    url = '/page/search/'
    weight = 3
    [zh-tw.menu.main.params]
      icon = 'search'
  [[zh-tw.menu.main]]
    identifier = 'about'
    name = '關於'
    url = '/page/about/'
    weight = 4
    [zh-tw.menu.main.params]
      icon = 'copyright'

[zh-cn]
  languageCode = 'zh-CN'
  languageName = '中文简体'
  title = 'Wayne 的博客'
  weight = 2
  [zh-cn.params]
    [zh-cn.params.sidebar]
      subtitle = '记录并分享日常'
  [[zh-cn.menu.main]]
    identifier = 'home'
    name = '主页'
    url = '/zh-cn/'
    weight = 1
    [zh-cn.menu.main.params]
      icon = 'home'
  [[zh-cn.menu.main]]
    identifier = 'archives'
    name = '归档'
    url = '/zh-cn/page/archives/'
    weight = 2
    [zh-cn.menu.main.params]
      icon = 'archives'
  [[zh-cn.menu.main]]
    identifier = 'search'
    name = '搜索'
    url = '/zh-cn/page/search/'
    weight = 3
    [zh-cn.menu.main.params]
      icon = 'search'
  [[zh-cn.menu.main]]
    identifier = 'about'
    name = '关于'
    url = '/zh-cn/page/about/'
    weight = 4
    [zh-cn.menu.main.params]
      icon = 'copyright'

[en]
  languageCode = 'en'
  languageName = 'English'
  title = "Wayne's Blog"
  weight = 3
  [en.params]
    [en.params.sidebar]
      subtitle = 'Record and share daily life'
  [[en.menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/en/'
    weight = 1
    [en.menu.main.params]
      icon = 'home'
  [[en.menu.main]]
    identifier = 'archives'
    name = 'Archives'
    url = '/en/page/archives/'
    weight = 2
    [en.menu.main.params]
      icon = 'archives'
  [[en.menu.main]]
    identifier = 'search'
    name = 'Search'
    url = '/en/page/search/'
    weight = 3
    [en.menu.main.params]
      icon = 'search'
  [[en.menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/en/page/about/'
    weight = 4
    [en.menu.main.params]
      icon = 'copyright'

[ja]
  languageCode = 'ja'
  languageName = '日本語'
  title = 'Wayneのブログ'
  weight = 4
  [ja.params]
    [ja.params.sidebar]
      subtitle = '日常を記録し共有する'
  [[ja.menu.main]]
    identifier = 'home'
    name = 'ホーム'
    url = '/ja/'
    weight = 1
    [ja.menu.main.params]
      icon = 'home'
  [[ja.menu.main]]
    identifier = 'archives'
    name = 'アーカイブ'
    url = '/ja/page/archives/'
    weight = 2
    [ja.menu.main.params]
      icon = 'archives'
  [[ja.menu.main]]
    identifier = 'search'
    name = '検索'
    url = '/ja/page/search/'
    weight = 3
    [ja.menu.main.params]
      icon = 'search'
  [[ja.menu.main]]
    identifier = 'about'
    name = '自己紹介'
    url = '/ja/page/about/'
    weight = 4
    [ja.menu.main.params]
      icon = 'copyright'

[es]
  languageCode = 'es'
  languageName = 'Español'
  title = 'Blog de Wayne'
  weight = 5
  [es.params]
    [es.params.sidebar]
      subtitle = 'Registrar y compartir la vida diaria'
  [[es.menu.main]]
    identifier = 'home'
    name = 'Inicio'
    url = '/es/'
    weight = 1
    [es.menu.main.params]
      icon = 'home'
  [[es.menu.main]]
    identifier = 'archives'
    name = 'Archivo'
    url = '/es/page/archives/'
    weight = 2
    [es.menu.main.params]
      icon = 'archives'
  [[es.menu.main]]
    identifier = 'search'
    name = 'Buscar'
    url = '/es/page/search/'
    weight = 3
    [es.menu.main.params]
      icon = 'search'
  [[es.menu.main]]
    identifier = 'about'
    name = 'Acerca de'
    url = '/es/page/about/'
    weight = 4
    [es.menu.main.params]
      icon = 'copyright'
